services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: smokebreakidea-app
    container_name: smokebreakidea-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini
    networks:
      - smokebreakidea-network

  nginx:
    image: nginx:alpine
    container_name: smokebreakidea-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d
    networks:
      - smokebreakidea-network
    depends_on:
      - app

  mysql:
    image: mysql:8.0
    container_name: smokebreakidea-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: smokebreakidea_db
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_PASSWORD: secret
      MYSQL_USER: smokebreakidea_user
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - smokebreakidea-network

  node:
    build:
      context: .
      dockerfile: Dockerfile.node
    container_name: smokebreakidea-node
    volumes:
      - ./:/var/www
    working_dir: /var/www
    tty: true
    stdin_open: true
    command: tail -f /dev/null
    networks:
      - smokebreakidea-network

volumes:
  mysql_data:
    driver: local

networks:
  smokebreakidea-network:
    driver: bridge